name: Cypress: Single File Test

on:
  workflow_dispatch:

jobs:
  run-single:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Show Cypress test file exists
        run: ls -la cypress/e2e

      - name: Run specific test
        run: npx cypress run --spec "**/F_project*.cy.js"
