name: Run Cypress - Single Test File

on:
  schedule:
    - cron: "0 12 * * *"  # 🕛 Daily at 12PM UTC
  workflow_dispatch:      # Optional: manual trigger button

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run specific Cypress test
        run: npx cypress run --spec "cypress/e2e/F_project.cy.js"
